blueprint:
  name: Simple Climate
  description: Automation to control thermostat presets based on a custom schedule
  domain: automation
  input:
    thermostat_entity:
      name: Thermostat entity
      description: Select the thermostat to control
      selector:
        entity:
          domain: climate
    kill_switch:
      name: Load shedding switch
      description: Select the switch to enable or disable load shedding
      selector:
        entity:
          domain: switch
    schedule_entity:
      name: Schedule entity
      description: Select the "schedule" entity used to plan the heating
      selector:
        entity:
          domain: schedule
    preset_when_on:
      name: Preset when schedule is active
      description: Select the preset when the schedule is in the "on" state
      selector:
        select:
          options:
            - 'comfort'
            - 'eco'
            - 'sleep'
            - 'away'
            - 'home'
    preset_when_off:
      name: Preset when schedule is inactive
      description: Select the preset when the schedule is in the "off" state
      selector:
        select:
          options:
            - 'comfort'
            - 'eco'
            - 'sleep'
            - 'away'
            - 'home'

mode: restart
max_exceeded: silent

trigger:
  - platform: state
    entity_id: !input schedule_entity
  - platform: state
    entity_id: !input kill_switch

condition: []

action:
  - choose:
      - conditions:
          - condition: state
            entity_id: !input kill_switch
            state: "off"
          - condition: state
            entity_id: !input schedule_entity
            state: "on"
        sequence:
          - service: climate.set_preset_mode
            target:
              entity_id: !input thermostat_entity
            data:
              preset_mode: !input preset_when_on
      - conditions:
          - condition: state
            entity_id: !input kill_switch
            state: "off"
          - condition: state
            entity_id: !input schedule_entity
            state: "off"
        sequence:
          - service: climate.set_preset_mode
            target:
              entity_id: !input thermostat_entity
            data:
              preset_mode: !input preset_when_off
      - conditions:
          - condition: state
            entity_id: !input kill_switch
            state: "on"
        sequence:
          - action: climate.turn_off
            data: {}
            target:
              entity_id: !input thermostat_entity
